# Generated by Django 3.2.13 on 2023-05-12 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='sum',
            field=models.FloatField(default=0),
        ),
    ]
