# Generated by Django 3.2.13 on 2023-05-12 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_sum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='sum',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
