# Generated by Django 3.2.13 on 2023-05-12 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_sum'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='sum',
            new_name='summ',
        ),
    ]
